artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/aviralsoni22/Chicken-Doctor/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion